services:
  - type: web
    name: aura-softphone-api
    env: node
    rootDir: api
    plan: starter
    envVars:
      - key: NODE_VERSION
        value: "20"
    buildCommand: npm install && npm run build
    startCommand: npm run start
